### ISSUE TITLE
Improve Error Reporting on Wrong Keys while Decrypting

### ISSUE THREAD

**Issue by alexanderkiel** [life-research/csv-crypt#6]
I got this exception while using a wrong key:

```
Exception in thread "main" com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_EMBEDDED_OBJECT
 at [Source: (byte[])"V��-��9�  �3��"; line: -1, column: 16]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:588)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:565)
        at com.fasterxml.jackson.dataformat.cbor.CBORParser.loadMoreGuaranteed(CBORParser.java:3006)
        at com.fasterxml.jackson.dataformat.cbor.CBORParser._finishBytes(CBORParser.java:2242)
        at com.fasterxml.jackson.dataformat.cbor.CBORParser._finishToken(CBORParser.java:1881)
        at com.fasterxml.jackson.dataformat.cbor.CBORParser.getBinaryValue(CBORParser.java:1447)
        at com.fasterxml.jackson.core.JsonParser.getBinaryValue(JsonParser.java:1442)
        at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:70)
        at cheshire.parse$parse_STAR_.invoke(parse.clj:61)
        at cheshire.parse$parse.invokeStatic(parse.clj:98)
        at cheshire.parse$parse.invoke(parse.clj:86)
        at cheshire.core$parse_cbor.invokeStatic(core.clj:283)
        at cheshire.core$parse_cbor.invoke(core.clj:272)
        at cheshire.core$parse_cbor.invokeStatic(core.clj:279)
        at cheshire.core$parse_cbor.invoke(core.clj:272)
        at csv_crypt.core$decrypt_line.invokeStatic(core.clj:70)
        at csv_crypt.core$decrypt_line.invoke(core.clj:55)
        at csv_crypt.core$decrypt_file$fn__2164.invoke(core.clj:92)
        at clojure.core$map$fn__5583$fn__5584.invoke(core.clj:2734)
        at clojure.core.protocols$fn__7852.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__7852.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__7807$G__7802__7816.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$transduce.invokeStatic(core.clj:6804)
        at clojure.core$into.invokeStatic(core.clj:6819)
        at clojure.core$into.invoke(core.clj:6807)
        at csv_crypt.core$read_csv.invokeStatic(core.clj:32)
        at csv_crypt.core$read_csv.invoke(core.clj:28)
        at csv_crypt.core$decrypt_file.invokeStatic(core.clj:92)
        at csv_crypt.core$decrypt_file.invoke(core.clj:84)
        at csv_crypt.core$_main.invokeStatic(core.clj:152)
        at csv_crypt.core$_main.doInvoke(core.clj:126)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at csv_crypt.core.main(Unknown Source)
```

**Comment by alexanderkiel** [comment]
Closed with 2cb6328
